kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  namespace: database
  labels:
    type: local
    app: postgres
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/postgres"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  namespace: database
  labels:
    app: postgres
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi