---
# Headless service for K3S metrics. No selector
apiVersion: v1
kind: Service
metadata:
  name: metrics-service
  labels:
    app: metrics
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 10249
    protocol: TCP
    targetPort: 10249
  type: ClusterIP
---
# Endpoint for the headless service without selector
apiVersion: v1
kind: Endpoints
metadata:
  name: metrics-service
  namespace: kube-system
subsets:
- addresses:
  - ip: 10.0.0.11
  ports:
  - name: http-metrics
    port: 10249
    protocol: TCP