apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: k3s
    release: kube-prometheus-stack
  name: prometheus-servicemonitor
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app: k3s-metrics
  endpoints:
    - port: http-metrics
      path: /metrics